### ISSUE TITLE
Error when tapping the floating button in co-browsing mode

### ISSUE THREAD

**Issue by nashfive** [unblu/ios-sdk-xcframeworks#2]
Hi,

I'm facing an issue after I enter the co-browsing mode. Once the co-browsing mode is started, I hide the Unblu UIView and I can see the green frame around my app and the conversation floating button. I can move it around, but as soon as I tap it, I get this error in the console: 

`2023-06-15 14:50:01.454489+0200 TestUnblu[1260:25769] [View] First responder issue detected: non-key window attempting reload - allowing due to manual keyboard (first responder window is <UnbluMobileCoBrowsingModule.FloatingButtonWindow: 0x102d0e4f0; baseClass = UIWindow; frame = (0 0; 375 667); autoresize = W+H; gestureRecognizers = <NSArray: 0x2811ce670>; layer = <UIWindowLayer: 0x2811ce4c0>>, key window is <UIWindow: 0x101615620; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x2810b0960>; layer = <UIWindowLayer: 0x2810b1200>>)`

My app is 100% SwiftUI and I am using the 4.6.1 version of the SDK. 

Can you reproduce the issue?

**Comment by indaos** [comment]
Hi! 
Yes, we can reproduce this problem, and a solution has already been found. 
An updated version will appear today.
Thanks for the bug report.
