### ISSUE TITLE
(Mobile CoBrowsing) Private area is duplicated and added/anchored to the floating button

### ISSUE THREAD

**Issue by nashfive** [unblu/ios-sdk-xcframeworks#3]
I am trying to add a private area on my CoBrowsing module with this simple code : 

```swift
let area = coBrowsingModule.addPrivateArea(withId: "test", x: 20, y: 20, width: 200, height: 100)
print("added private area: \(area.id), rect: \(area.rect)")
```
which successfully outputs: `added private area: test, rect: (20.0, 20.0, 200.0, 100.0)` in my console.

Then I start a co-mobile session, and I see this on the agent side: 

![Screenshot 2023-07-10 at 15 53 43](https://github.com/unblu/ios-sdk-xcframeworks/assets/50933/530e96f9-7a7c-4d12-ac40-eeec0f090b48)

it seems that private areas are somewhat duplicated? The one in the top corner is the correct one. What about the second one? Where does it come from? It seems "anchored" to the floating button apparently because if I drag and move the button, the second private area moves with it. 

Can you check? It looks like a bug on your side...
I am using the 4.7.2 version of your SDK, in a SwiftUI 3 project (iOS 15 min)

**Comment by indaos** [comment]
try to use frameworks from the main branch instead of the release version. this issue has been fixed, and the fix has been present in the main branch for some time but has not yet been released.
