### ISSUE TITLE
Memory issue after calling stop() on UnbluVisitorClient

### ISSUE THREAD

**Issue by nashfive** [unblu/ios-sdk-xcframeworks#4]
Hi @indaos !

I've noticed that the SDK still makes calls to the Unblu backend, even though the unbluView is not displayed and the stop() method has been called.
It seems that a lot of things stay in memory and are still doing many calls. This is quite concerning. 

Is it something that is expected or by design ? 

Here is a simple SwiftUI example to reproduce the issue: 

```swift
@main struct UnbluTestApp: App {
    var body: some Scene { WindowGroup { ContentView() } }
}

struct ContentView: View {
    @State private var showLiveChat = false

    var body: some View {
        Button("Start live chat") { showLiveChat = true }
            .sheet(isPresented: $showLiveChat, content: LiveChatView.init)
    }
}

struct LiveChatView: View {
    @StateObject private var model = LiveChatViewModel()

    var body: some View {
        Representable(uiView: model.unbluView)
            .onAppear(perform: model.start)
            .onDisappear(perform: model.stop)
    }
}

final class LiveChatViewModel: ObservableObject, UnbluVisitorClientDelegate {
    private lazy var visitor: UnbluVisitorClient = Unblu.createVisitorClient(
            withConfiguration: .init(
                unbluBaseUrl: baseUrl,
                apiKey: apiKey,
                preferencesStorage: UserDefaultsPreferencesStorage(),
                fileDownloadHandler: UnbluDefaultFileDownloadHandler(),
                externalLinkHandler: UnbluDefaultExternalLinkHandler()))

    init() {
        visitor.visitorDelegate = self
    }

    var unbluView: UIView { visitor.view }
    func start() { visitor.start { print($0) } }
    func stop() {
        visitor.stop { [weak visitor] in
            print($0)
            visitor?.visitorDelegate = nil
        }
    }

    func unbluDidInitialize() { print("unbluDidInitialize") }
    func unbluDidDeinitialize() { print("unbluDidDeinitialize") }
    func unblu(didUpdatePersonActivityInfo personActivity: UnbluCoreSDK.PersonActivityInfo) {}
    deinit { print("deinit") }
}

struct Representable<Content: UIView>: UIViewRepresentable {
    let uiView: Content
    init(uiView content: @autoclosure () -> Content) {
        uiView = content()
    }
    func makeUIView(context: Context) -> some UIView { uiView }
    func updateUIView(_ uiView: UIViewType, context: Context) {}
}
```

When I dismiss the sheet, the call to `visitor.stop()` is a success and I can see from my console log that : 
- the delegate method `unbluDidDeinitialize()` is called
- the `deinit` method of my ObservableObject is called
- I also get a `[INFO](UnbluCoreApi): UnbluCoreApi deinitialized!` log from the SDK

But, when I use a network sniffer, I can still see many calls to the Unblu backend that are made every seconds.
 
When I inspect the memory graph, I can see that many Unblu objects are still loaded in memory (if not all of them!), especially the web view which seems to continue triggering api calls and events. It looks like the Unblu view is not properly "reset"...
![unblu-memgraph](https://github.com/unblu/ios-sdk-xcframeworks/assets/50933/3bea4920-2916-4f85-91ad-a0b02859af57)

Can you have a look at this ?

**Comment by indaos** [comment]
Thank you for the note, I will look into the problem you described soon

**Comment by nashfive** [comment]
Hi @indaos, any news on that front ? :)

**Comment by indaos** [comment]
Sorry for the delay, I will let you know something within this or next week

**Comment by indaos** [comment]
I found a retain cycle that appeared recently, now it's fixed, I think it should already be fixed in the main branch, and the release will be next week

**Comment by nashfive** [comment]
@indaos Good, I am looking forward to the new release.
Quick question on the side, I believe you also custom builds of your SDK (my client is ZVV) and we are using the builds coming from this GitHub package, not the one I can find on delivery.unblu.com. I was wondering, have you already implemented custom features/settings in my client's custom releases or can I keep using the builds in this public Github repo ?

**Comment by indaos** [comment]
Regardless of how you get these frameworks, they are the same. There is no custom build for ZVV, so you can continue to use the builds downloaded from here.

**Comment by nashfive** [comment]
Hello @indaos, is this issue fixed in the recent 4.7.5 version? Where can I find a meaningful changelog for each release? I can't find anything on this github or on Unblu's servicedesk website 😐

**Comment by indaos** [comment]
Hi!
https://www.unblu.com/en/docs/latest/release-notes/mobile-sdk-ios.html#ios-mobile-sdk-4-7-5-release-notes

**Comment by nashfive** [comment]
Awesome! thanks. 
Case closed, the issue is gone with the new release 👍🏻
